/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as HqLoginRouteImport } from './routes/hq-login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClientLoginRouteImport } from './routes/client-login'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as HqRouteImport } from './routes/_hq'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as DivisionsIndexRouteImport } from './routes/divisions.index'
import { Route as PortalMessagesRouteImport } from './routes/portal.messages'
import { Route as PortalJobsRouteImport } from './routes/portal.jobs'
import { Route as PortalInvoicesRouteImport } from './routes/portal.invoices'
import { Route as PortalDocumentsRouteImport } from './routes/portal.documents'
import { Route as MeetingIdRouteImport } from './routes/meeting.$id'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as HelpSlugRouteImport } from './routes/help.$slug'
import { Route as DivisionsSlugRouteImport } from './routes/divisions.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as HqWarrantyClaimsRouteImport } from './routes/_hq.warranty-claims'
import { Route as HqTrainingRouteImport } from './routes/_hq.training'
import { Route as HqTimeTrackingRouteImport } from './routes/_hq.time-tracking'
import { Route as HqTimeOffRouteImport } from './routes/_hq.time-off'
import { Route as HqTicketsRouteImport } from './routes/_hq.tickets'
import { Route as HqTasksRouteImport } from './routes/_hq.tasks'
import { Route as HqTakeoffsRouteImport } from './routes/_hq.takeoffs'
import { Route as HqSuppliersRouteImport } from './routes/_hq.suppliers'
import { Route as HqSubcontractorsRouteImport } from './routes/_hq.subcontractors'
import { Route as HqSettingsRouteImport } from './routes/_hq.settings'
import { Route as HqSearchRouteImport } from './routes/_hq.search'
import { Route as HqSalesAnalyticsRouteImport } from './routes/_hq.sales-analytics'
import { Route as HqSafetyRouteImport } from './routes/_hq.safety'
import { Route as HqRfisRouteImport } from './routes/_hq.rfis'
import { Route as HqReviewsRouteImport } from './routes/_hq.reviews'
import { Route as HqResourcePlanningRouteImport } from './routes/_hq.resource-planning'
import { Route as HqReceivingRouteImport } from './routes/_hq.receiving'
import { Route as HqRdIdeasRouteImport } from './routes/_hq.rd-ideas'
import { Route as HqQuotesRouteImport } from './routes/_hq.quotes'
import { Route as HqPurchaseOrdersRouteImport } from './routes/_hq.purchase-orders'
import { Route as HqPunchListRouteImport } from './routes/_hq.punch-list'
import { Route as HqProposalsRouteImport } from './routes/_hq.proposals'
import { Route as HqProfileRouteImport } from './routes/_hq.profile'
import { Route as HqPlansRouteImport } from './routes/_hq.plans'
import { Route as HqPipelineRouteImport } from './routes/_hq.pipeline'
import { Route as HqPhoneRouteImport } from './routes/_hq.phone'
import { Route as HqPermitsRouteImport } from './routes/_hq.permits'
import { Route as HqOrgChartRouteImport } from './routes/_hq.org-chart'
import { Route as HqOnboardingRouteImport } from './routes/_hq.onboarding'
import { Route as HqNotificationsRouteImport } from './routes/_hq.notifications'
import { Route as HqMeetingsRouteImport } from './routes/_hq.meetings'
import { Route as HqMeetingNotesRouteImport } from './routes/_hq.meeting-notes'
import { Route as HqMailRouteImport } from './routes/_hq.mail'
import { Route as HqLiveChatRouteImport } from './routes/_hq.live-chat'
import { Route as HqLeadsRouteImport } from './routes/_hq.leads'
import { Route as HqKbRouteImport } from './routes/_hq.kb'
import { Route as HqJobsRouteImport } from './routes/_hq.jobs'
import { Route as HqJobCostingRouteImport } from './routes/_hq.job-costing'
import { Route as HqInvoicesRouteImport } from './routes/_hq.invoices'
import { Route as HqInventoryRouteImport } from './routes/_hq.inventory'
import { Route as HqInspectionsRouteImport } from './routes/_hq.inspections'
import { Route as HqHiringRouteImport } from './routes/_hq.hiring'
import { Route as HqHelpRouteImport } from './routes/_hq.help'
import { Route as HqFinancialReportsRouteImport } from './routes/_hq.financial-reports'
import { Route as HqExpensesRouteImport } from './routes/_hq.expenses'
import { Route as HqEquipmentRouteImport } from './routes/_hq.equipment'
import { Route as HqEngProjectsRouteImport } from './routes/_hq.eng-projects'
import { Route as HqEmployeesRouteImport } from './routes/_hq.employees'
import { Route as HqDriveRouteImport } from './routes/_hq.drive'
import { Route as HqDmRouteImport } from './routes/_hq.dm'
import { Route as HqDeliveriesRouteImport } from './routes/_hq.deliveries'
import { Route as HqDashboardRouteImport } from './routes/_hq.dashboard'
import { Route as HqDailyLogsRouteImport } from './routes/_hq.daily-logs'
import { Route as HqCustomerTimelineRouteImport } from './routes/_hq.customer-timeline'
import { Route as HqCrewsRouteImport } from './routes/_hq.crews'
import { Route as HqCompanyTasksRouteImport } from './routes/_hq.company-tasks'
import { Route as HqClientsRouteImport } from './routes/_hq.clients'
import { Route as HqChannelsRouteImport } from './routes/_hq.channels'
import { Route as HqChangeOrdersRouteImport } from './routes/_hq.change-orders'
import { Route as HqCertificationsRouteImport } from './routes/_hq.certifications'
import { Route as HqCalendarRouteImport } from './routes/_hq.calendar'
import { Route as HqAssistantRouteImport } from './routes/_hq.assistant'
import { Route as HqApplicantsRouteImport } from './routes/_hq.applicants'
import { Route as HqAnalyticsRouteImport } from './routes/_hq.analytics'
import { Route as HqAccountingRouteImport } from './routes/_hq.accounting'
import { Route as HqQuotesIndexRouteImport } from './routes/_hq.quotes.index'
import { Route as HqJobsIndexRouteImport } from './routes/_hq.jobs.index'
import { Route as HqClientsIndexRouteImport } from './routes/_hq.clients.index'
import { Route as ApiHqAssistantRouteImport } from './routes/api/hq/assistant'
import { Route as HqQuotesIdRouteImport } from './routes/_hq.quotes.$id'
import { Route as HqJobsIdRouteImport } from './routes/_hq.jobs.$id'
import { Route as HqClientsIdRouteImport } from './routes/_hq.clients.$id'
import { Route as HqAdminDepartmentsRouteImport } from './routes/_hq.admin.departments'
import { Route as HqAdminCompanyRouteImport } from './routes/_hq.admin.company'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const HqLoginRoute = HqLoginRouteImport.update({
  id: '/hq-login',
  path: '/hq-login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLoginRoute = ClientLoginRouteImport.update({
  id: '/client-login',
  path: '/client-login',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const HqRoute = HqRouteImport.update({
  id: '/_hq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const DivisionsIndexRoute = DivisionsIndexRouteImport.update({
  id: '/divisions/',
  path: '/divisions/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalMessagesRoute = PortalMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PortalRoute,
} as any)
const PortalJobsRoute = PortalJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => PortalRoute,
} as any)
const PortalInvoicesRoute = PortalInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentsRoute = PortalDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PortalRoute,
} as any)
const MeetingIdRoute = MeetingIdRouteImport.update({
  id: '/meeting/$id',
  path: '/meeting/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpSlugRoute = HelpSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HelpRoute,
} as any)
const DivisionsSlugRoute = DivisionsSlugRouteImport.update({
  id: '/divisions/$slug',
  path: '/divisions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const HqWarrantyClaimsRoute = HqWarrantyClaimsRouteImport.update({
  id: '/warranty-claims',
  path: '/warranty-claims',
  getParentRoute: () => HqRoute,
} as any)
const HqTrainingRoute = HqTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => HqRoute,
} as any)
const HqTimeTrackingRoute = HqTimeTrackingRouteImport.update({
  id: '/time-tracking',
  path: '/time-tracking',
  getParentRoute: () => HqRoute,
} as any)
const HqTimeOffRoute = HqTimeOffRouteImport.update({
  id: '/time-off',
  path: '/time-off',
  getParentRoute: () => HqRoute,
} as any)
const HqTicketsRoute = HqTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => HqRoute,
} as any)
const HqTasksRoute = HqTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => HqRoute,
} as any)
const HqTakeoffsRoute = HqTakeoffsRouteImport.update({
  id: '/takeoffs',
  path: '/takeoffs',
  getParentRoute: () => HqRoute,
} as any)
const HqSuppliersRoute = HqSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => HqRoute,
} as any)
const HqSubcontractorsRoute = HqSubcontractorsRouteImport.update({
  id: '/subcontractors',
  path: '/subcontractors',
  getParentRoute: () => HqRoute,
} as any)
const HqSettingsRoute = HqSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HqRoute,
} as any)
const HqSearchRoute = HqSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => HqRoute,
} as any)
const HqSalesAnalyticsRoute = HqSalesAnalyticsRouteImport.update({
  id: '/sales-analytics',
  path: '/sales-analytics',
  getParentRoute: () => HqRoute,
} as any)
const HqSafetyRoute = HqSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => HqRoute,
} as any)
const HqRfisRoute = HqRfisRouteImport.update({
  id: '/rfis',
  path: '/rfis',
  getParentRoute: () => HqRoute,
} as any)
const HqReviewsRoute = HqReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => HqRoute,
} as any)
const HqResourcePlanningRoute = HqResourcePlanningRouteImport.update({
  id: '/resource-planning',
  path: '/resource-planning',
  getParentRoute: () => HqRoute,
} as any)
const HqReceivingRoute = HqReceivingRouteImport.update({
  id: '/receiving',
  path: '/receiving',
  getParentRoute: () => HqRoute,
} as any)
const HqRdIdeasRoute = HqRdIdeasRouteImport.update({
  id: '/rd-ideas',
  path: '/rd-ideas',
  getParentRoute: () => HqRoute,
} as any)
const HqQuotesRoute = HqQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => HqRoute,
} as any)
const HqPurchaseOrdersRoute = HqPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => HqRoute,
} as any)
const HqPunchListRoute = HqPunchListRouteImport.update({
  id: '/punch-list',
  path: '/punch-list',
  getParentRoute: () => HqRoute,
} as any)
const HqProposalsRoute = HqProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => HqRoute,
} as any)
const HqProfileRoute = HqProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => HqRoute,
} as any)
const HqPlansRoute = HqPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => HqRoute,
} as any)
const HqPipelineRoute = HqPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => HqRoute,
} as any)
const HqPhoneRoute = HqPhoneRouteImport.update({
  id: '/phone',
  path: '/phone',
  getParentRoute: () => HqRoute,
} as any)
const HqPermitsRoute = HqPermitsRouteImport.update({
  id: '/permits',
  path: '/permits',
  getParentRoute: () => HqRoute,
} as any)
const HqOrgChartRoute = HqOrgChartRouteImport.update({
  id: '/org-chart',
  path: '/org-chart',
  getParentRoute: () => HqRoute,
} as any)
const HqOnboardingRoute = HqOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => HqRoute,
} as any)
const HqNotificationsRoute = HqNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => HqRoute,
} as any)
const HqMeetingsRoute = HqMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => HqRoute,
} as any)
const HqMeetingNotesRoute = HqMeetingNotesRouteImport.update({
  id: '/meeting-notes',
  path: '/meeting-notes',
  getParentRoute: () => HqRoute,
} as any)
const HqMailRoute = HqMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => HqRoute,
} as any)
const HqLiveChatRoute = HqLiveChatRouteImport.update({
  id: '/live-chat',
  path: '/live-chat',
  getParentRoute: () => HqRoute,
} as any)
const HqLeadsRoute = HqLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => HqRoute,
} as any)
const HqKbRoute = HqKbRouteImport.update({
  id: '/kb',
  path: '/kb',
  getParentRoute: () => HqRoute,
} as any)
const HqJobsRoute = HqJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => HqRoute,
} as any)
const HqJobCostingRoute = HqJobCostingRouteImport.update({
  id: '/job-costing',
  path: '/job-costing',
  getParentRoute: () => HqRoute,
} as any)
const HqInvoicesRoute = HqInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => HqRoute,
} as any)
const HqInventoryRoute = HqInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => HqRoute,
} as any)
const HqInspectionsRoute = HqInspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => HqRoute,
} as any)
const HqHiringRoute = HqHiringRouteImport.update({
  id: '/hiring',
  path: '/hiring',
  getParentRoute: () => HqRoute,
} as any)
const HqHelpRoute = HqHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => HqRoute,
} as any)
const HqFinancialReportsRoute = HqFinancialReportsRouteImport.update({
  id: '/financial-reports',
  path: '/financial-reports',
  getParentRoute: () => HqRoute,
} as any)
const HqExpensesRoute = HqExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => HqRoute,
} as any)
const HqEquipmentRoute = HqEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => HqRoute,
} as any)
const HqEngProjectsRoute = HqEngProjectsRouteImport.update({
  id: '/eng-projects',
  path: '/eng-projects',
  getParentRoute: () => HqRoute,
} as any)
const HqEmployeesRoute = HqEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => HqRoute,
} as any)
const HqDriveRoute = HqDriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => HqRoute,
} as any)
const HqDmRoute = HqDmRouteImport.update({
  id: '/dm',
  path: '/dm',
  getParentRoute: () => HqRoute,
} as any)
const HqDeliveriesRoute = HqDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => HqRoute,
} as any)
const HqDashboardRoute = HqDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => HqRoute,
} as any)
const HqDailyLogsRoute = HqDailyLogsRouteImport.update({
  id: '/daily-logs',
  path: '/daily-logs',
  getParentRoute: () => HqRoute,
} as any)
const HqCustomerTimelineRoute = HqCustomerTimelineRouteImport.update({
  id: '/customer-timeline',
  path: '/customer-timeline',
  getParentRoute: () => HqRoute,
} as any)
const HqCrewsRoute = HqCrewsRouteImport.update({
  id: '/crews',
  path: '/crews',
  getParentRoute: () => HqRoute,
} as any)
const HqCompanyTasksRoute = HqCompanyTasksRouteImport.update({
  id: '/company-tasks',
  path: '/company-tasks',
  getParentRoute: () => HqRoute,
} as any)
const HqClientsRoute = HqClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => HqRoute,
} as any)
const HqChannelsRoute = HqChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => HqRoute,
} as any)
const HqChangeOrdersRoute = HqChangeOrdersRouteImport.update({
  id: '/change-orders',
  path: '/change-orders',
  getParentRoute: () => HqRoute,
} as any)
const HqCertificationsRoute = HqCertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => HqRoute,
} as any)
const HqCalendarRoute = HqCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => HqRoute,
} as any)
const HqAssistantRoute = HqAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => HqRoute,
} as any)
const HqApplicantsRoute = HqApplicantsRouteImport.update({
  id: '/applicants',
  path: '/applicants',
  getParentRoute: () => HqRoute,
} as any)
const HqAnalyticsRoute = HqAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => HqRoute,
} as any)
const HqAccountingRoute = HqAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => HqRoute,
} as any)
const HqQuotesIndexRoute = HqQuotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HqQuotesRoute,
} as any)
const HqJobsIndexRoute = HqJobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HqJobsRoute,
} as any)
const HqClientsIndexRoute = HqClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HqClientsRoute,
} as any)
const ApiHqAssistantRoute = ApiHqAssistantRouteImport.update({
  id: '/api/hq/assistant',
  path: '/api/hq/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const HqQuotesIdRoute = HqQuotesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HqQuotesRoute,
} as any)
const HqJobsIdRoute = HqJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HqJobsRoute,
} as any)
const HqClientsIdRoute = HqClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HqClientsRoute,
} as any)
const HqAdminDepartmentsRoute = HqAdminDepartmentsRouteImport.update({
  id: '/admin/departments',
  path: '/admin/departments',
  getParentRoute: () => HqRoute,
} as any)
const HqAdminCompanyRoute = HqAdminCompanyRouteImport.update({
  id: '/admin/company',
  path: '/admin/company',
  getParentRoute: () => HqRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/client-login': typeof ClientLoginRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/help': typeof HqHelpRoute
  '/hq-login': typeof HqLoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/process': typeof ProcessRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/accounting': typeof HqAccountingRoute
  '/analytics': typeof HqAnalyticsRoute
  '/applicants': typeof HqApplicantsRoute
  '/assistant': typeof HqAssistantRoute
  '/calendar': typeof HqCalendarRoute
  '/certifications': typeof HqCertificationsRoute
  '/change-orders': typeof HqChangeOrdersRoute
  '/channels': typeof HqChannelsRoute
  '/clients': typeof HqClientsRouteWithChildren
  '/company-tasks': typeof HqCompanyTasksRoute
  '/crews': typeof HqCrewsRoute
  '/customer-timeline': typeof HqCustomerTimelineRoute
  '/daily-logs': typeof HqDailyLogsRoute
  '/dashboard': typeof HqDashboardRoute
  '/deliveries': typeof HqDeliveriesRoute
  '/dm': typeof HqDmRoute
  '/drive': typeof HqDriveRoute
  '/employees': typeof HqEmployeesRoute
  '/eng-projects': typeof HqEngProjectsRoute
  '/equipment': typeof HqEquipmentRoute
  '/expenses': typeof HqExpensesRoute
  '/financial-reports': typeof HqFinancialReportsRoute
  '/hiring': typeof HqHiringRoute
  '/inspections': typeof HqInspectionsRoute
  '/inventory': typeof HqInventoryRoute
  '/invoices': typeof HqInvoicesRoute
  '/job-costing': typeof HqJobCostingRoute
  '/jobs': typeof HqJobsRouteWithChildren
  '/kb': typeof HqKbRoute
  '/leads': typeof HqLeadsRoute
  '/live-chat': typeof HqLiveChatRoute
  '/mail': typeof HqMailRoute
  '/meeting-notes': typeof HqMeetingNotesRoute
  '/meetings': typeof HqMeetingsRoute
  '/notifications': typeof HqNotificationsRoute
  '/onboarding': typeof HqOnboardingRoute
  '/org-chart': typeof HqOrgChartRoute
  '/permits': typeof HqPermitsRoute
  '/phone': typeof HqPhoneRoute
  '/pipeline': typeof HqPipelineRoute
  '/plans': typeof HqPlansRoute
  '/profile': typeof HqProfileRoute
  '/proposals': typeof HqProposalsRoute
  '/punch-list': typeof HqPunchListRoute
  '/purchase-orders': typeof HqPurchaseOrdersRoute
  '/quotes': typeof HqQuotesRouteWithChildren
  '/rd-ideas': typeof HqRdIdeasRoute
  '/receiving': typeof HqReceivingRoute
  '/resource-planning': typeof HqResourcePlanningRoute
  '/reviews': typeof HqReviewsRoute
  '/rfis': typeof HqRfisRoute
  '/safety': typeof HqSafetyRoute
  '/sales-analytics': typeof HqSalesAnalyticsRoute
  '/search': typeof HqSearchRoute
  '/settings': typeof HqSettingsRoute
  '/subcontractors': typeof HqSubcontractorsRoute
  '/suppliers': typeof HqSuppliersRoute
  '/takeoffs': typeof HqTakeoffsRoute
  '/tasks': typeof HqTasksRoute
  '/tickets': typeof HqTicketsRoute
  '/time-off': typeof HqTimeOffRoute
  '/time-tracking': typeof HqTimeTrackingRoute
  '/training': typeof HqTrainingRoute
  '/warranty-claims': typeof HqWarrantyClaimsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/divisions/$slug': typeof DivisionsSlugRoute
  '/help/$slug': typeof HelpSlugRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/meeting/$id': typeof MeetingIdRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/invoices': typeof PortalInvoicesRoute
  '/portal/jobs': typeof PortalJobsRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/divisions/': typeof DivisionsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/company': typeof HqAdminCompanyRoute
  '/admin/departments': typeof HqAdminDepartmentsRoute
  '/clients/$id': typeof HqClientsIdRoute
  '/jobs/$id': typeof HqJobsIdRoute
  '/quotes/$id': typeof HqQuotesIdRoute
  '/api/hq/assistant': typeof ApiHqAssistantRoute
  '/clients/': typeof HqClientsIndexRoute
  '/jobs/': typeof HqJobsIndexRoute
  '/quotes/': typeof HqQuotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/client-login': typeof ClientLoginRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/help': typeof HqHelpRoute
  '/hq-login': typeof HqLoginRoute
  '/process': typeof ProcessRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/accounting': typeof HqAccountingRoute
  '/analytics': typeof HqAnalyticsRoute
  '/applicants': typeof HqApplicantsRoute
  '/assistant': typeof HqAssistantRoute
  '/calendar': typeof HqCalendarRoute
  '/certifications': typeof HqCertificationsRoute
  '/change-orders': typeof HqChangeOrdersRoute
  '/channels': typeof HqChannelsRoute
  '/company-tasks': typeof HqCompanyTasksRoute
  '/crews': typeof HqCrewsRoute
  '/customer-timeline': typeof HqCustomerTimelineRoute
  '/daily-logs': typeof HqDailyLogsRoute
  '/dashboard': typeof HqDashboardRoute
  '/deliveries': typeof HqDeliveriesRoute
  '/dm': typeof HqDmRoute
  '/drive': typeof HqDriveRoute
  '/employees': typeof HqEmployeesRoute
  '/eng-projects': typeof HqEngProjectsRoute
  '/equipment': typeof HqEquipmentRoute
  '/expenses': typeof HqExpensesRoute
  '/financial-reports': typeof HqFinancialReportsRoute
  '/hiring': typeof HqHiringRoute
  '/inspections': typeof HqInspectionsRoute
  '/inventory': typeof HqInventoryRoute
  '/invoices': typeof HqInvoicesRoute
  '/job-costing': typeof HqJobCostingRoute
  '/kb': typeof HqKbRoute
  '/leads': typeof HqLeadsRoute
  '/live-chat': typeof HqLiveChatRoute
  '/mail': typeof HqMailRoute
  '/meeting-notes': typeof HqMeetingNotesRoute
  '/meetings': typeof HqMeetingsRoute
  '/notifications': typeof HqNotificationsRoute
  '/onboarding': typeof HqOnboardingRoute
  '/org-chart': typeof HqOrgChartRoute
  '/permits': typeof HqPermitsRoute
  '/phone': typeof HqPhoneRoute
  '/pipeline': typeof HqPipelineRoute
  '/plans': typeof HqPlansRoute
  '/profile': typeof HqProfileRoute
  '/proposals': typeof HqProposalsRoute
  '/punch-list': typeof HqPunchListRoute
  '/purchase-orders': typeof HqPurchaseOrdersRoute
  '/rd-ideas': typeof HqRdIdeasRoute
  '/receiving': typeof HqReceivingRoute
  '/resource-planning': typeof HqResourcePlanningRoute
  '/reviews': typeof HqReviewsRoute
  '/rfis': typeof HqRfisRoute
  '/safety': typeof HqSafetyRoute
  '/sales-analytics': typeof HqSalesAnalyticsRoute
  '/search': typeof HqSearchRoute
  '/settings': typeof HqSettingsRoute
  '/subcontractors': typeof HqSubcontractorsRoute
  '/suppliers': typeof HqSuppliersRoute
  '/takeoffs': typeof HqTakeoffsRoute
  '/tasks': typeof HqTasksRoute
  '/tickets': typeof HqTicketsRoute
  '/time-off': typeof HqTimeOffRoute
  '/time-tracking': typeof HqTimeTrackingRoute
  '/training': typeof HqTrainingRoute
  '/warranty-claims': typeof HqWarrantyClaimsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/divisions/$slug': typeof DivisionsSlugRoute
  '/help/$slug': typeof HelpSlugRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/meeting/$id': typeof MeetingIdRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/invoices': typeof PortalInvoicesRoute
  '/portal/jobs': typeof PortalJobsRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/divisions': typeof DivisionsIndexRoute
  '/portal': typeof PortalIndexRoute
  '/admin/company': typeof HqAdminCompanyRoute
  '/admin/departments': typeof HqAdminDepartmentsRoute
  '/clients/$id': typeof HqClientsIdRoute
  '/jobs/$id': typeof HqJobsIdRoute
  '/quotes/$id': typeof HqQuotesIdRoute
  '/api/hq/assistant': typeof ApiHqAssistantRoute
  '/clients': typeof HqClientsIndexRoute
  '/jobs': typeof HqJobsIndexRoute
  '/quotes': typeof HqQuotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_hq': typeof HqRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/client-login': typeof ClientLoginRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRouteWithChildren
  '/hq-login': typeof HqLoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/process': typeof ProcessRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_hq/accounting': typeof HqAccountingRoute
  '/_hq/analytics': typeof HqAnalyticsRoute
  '/_hq/applicants': typeof HqApplicantsRoute
  '/_hq/assistant': typeof HqAssistantRoute
  '/_hq/calendar': typeof HqCalendarRoute
  '/_hq/certifications': typeof HqCertificationsRoute
  '/_hq/change-orders': typeof HqChangeOrdersRoute
  '/_hq/channels': typeof HqChannelsRoute
  '/_hq/clients': typeof HqClientsRouteWithChildren
  '/_hq/company-tasks': typeof HqCompanyTasksRoute
  '/_hq/crews': typeof HqCrewsRoute
  '/_hq/customer-timeline': typeof HqCustomerTimelineRoute
  '/_hq/daily-logs': typeof HqDailyLogsRoute
  '/_hq/dashboard': typeof HqDashboardRoute
  '/_hq/deliveries': typeof HqDeliveriesRoute
  '/_hq/dm': typeof HqDmRoute
  '/_hq/drive': typeof HqDriveRoute
  '/_hq/employees': typeof HqEmployeesRoute
  '/_hq/eng-projects': typeof HqEngProjectsRoute
  '/_hq/equipment': typeof HqEquipmentRoute
  '/_hq/expenses': typeof HqExpensesRoute
  '/_hq/financial-reports': typeof HqFinancialReportsRoute
  '/_hq/help': typeof HqHelpRoute
  '/_hq/hiring': typeof HqHiringRoute
  '/_hq/inspections': typeof HqInspectionsRoute
  '/_hq/inventory': typeof HqInventoryRoute
  '/_hq/invoices': typeof HqInvoicesRoute
  '/_hq/job-costing': typeof HqJobCostingRoute
  '/_hq/jobs': typeof HqJobsRouteWithChildren
  '/_hq/kb': typeof HqKbRoute
  '/_hq/leads': typeof HqLeadsRoute
  '/_hq/live-chat': typeof HqLiveChatRoute
  '/_hq/mail': typeof HqMailRoute
  '/_hq/meeting-notes': typeof HqMeetingNotesRoute
  '/_hq/meetings': typeof HqMeetingsRoute
  '/_hq/notifications': typeof HqNotificationsRoute
  '/_hq/onboarding': typeof HqOnboardingRoute
  '/_hq/org-chart': typeof HqOrgChartRoute
  '/_hq/permits': typeof HqPermitsRoute
  '/_hq/phone': typeof HqPhoneRoute
  '/_hq/pipeline': typeof HqPipelineRoute
  '/_hq/plans': typeof HqPlansRoute
  '/_hq/profile': typeof HqProfileRoute
  '/_hq/proposals': typeof HqProposalsRoute
  '/_hq/punch-list': typeof HqPunchListRoute
  '/_hq/purchase-orders': typeof HqPurchaseOrdersRoute
  '/_hq/quotes': typeof HqQuotesRouteWithChildren
  '/_hq/rd-ideas': typeof HqRdIdeasRoute
  '/_hq/receiving': typeof HqReceivingRoute
  '/_hq/resource-planning': typeof HqResourcePlanningRoute
  '/_hq/reviews': typeof HqReviewsRoute
  '/_hq/rfis': typeof HqRfisRoute
  '/_hq/safety': typeof HqSafetyRoute
  '/_hq/sales-analytics': typeof HqSalesAnalyticsRoute
  '/_hq/search': typeof HqSearchRoute
  '/_hq/settings': typeof HqSettingsRoute
  '/_hq/subcontractors': typeof HqSubcontractorsRoute
  '/_hq/suppliers': typeof HqSuppliersRoute
  '/_hq/takeoffs': typeof HqTakeoffsRoute
  '/_hq/tasks': typeof HqTasksRoute
  '/_hq/tickets': typeof HqTicketsRoute
  '/_hq/time-off': typeof HqTimeOffRoute
  '/_hq/time-tracking': typeof HqTimeTrackingRoute
  '/_hq/training': typeof HqTrainingRoute
  '/_hq/warranty-claims': typeof HqWarrantyClaimsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/divisions/$slug': typeof DivisionsSlugRoute
  '/help/$slug': typeof HelpSlugRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/meeting/$id': typeof MeetingIdRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/invoices': typeof PortalInvoicesRoute
  '/portal/jobs': typeof PortalJobsRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/divisions/': typeof DivisionsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/_hq/admin/company': typeof HqAdminCompanyRoute
  '/_hq/admin/departments': typeof HqAdminDepartmentsRoute
  '/_hq/clients/$id': typeof HqClientsIdRoute
  '/_hq/jobs/$id': typeof HqJobsIdRoute
  '/_hq/quotes/$id': typeof HqQuotesIdRoute
  '/api/hq/assistant': typeof ApiHqAssistantRoute
  '/_hq/clients/': typeof HqClientsIndexRoute
  '/_hq/jobs/': typeof HqJobsIndexRoute
  '/_hq/quotes/': typeof HqQuotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/client-login'
    | '/contact'
    | '/faq'
    | '/help'
    | '/hq-login'
    | '/portal'
    | '/process'
    | '/projects'
    | '/services'
    | '/sitemap.xml'
    | '/accounting'
    | '/analytics'
    | '/applicants'
    | '/assistant'
    | '/calendar'
    | '/certifications'
    | '/change-orders'
    | '/channels'
    | '/clients'
    | '/company-tasks'
    | '/crews'
    | '/customer-timeline'
    | '/daily-logs'
    | '/dashboard'
    | '/deliveries'
    | '/dm'
    | '/drive'
    | '/employees'
    | '/eng-projects'
    | '/equipment'
    | '/expenses'
    | '/financial-reports'
    | '/hiring'
    | '/inspections'
    | '/inventory'
    | '/invoices'
    | '/job-costing'
    | '/jobs'
    | '/kb'
    | '/leads'
    | '/live-chat'
    | '/mail'
    | '/meeting-notes'
    | '/meetings'
    | '/notifications'
    | '/onboarding'
    | '/org-chart'
    | '/permits'
    | '/phone'
    | '/pipeline'
    | '/plans'
    | '/profile'
    | '/proposals'
    | '/punch-list'
    | '/purchase-orders'
    | '/quotes'
    | '/rd-ideas'
    | '/receiving'
    | '/resource-planning'
    | '/reviews'
    | '/rfis'
    | '/safety'
    | '/sales-analytics'
    | '/search'
    | '/settings'
    | '/subcontractors'
    | '/suppliers'
    | '/takeoffs'
    | '/tasks'
    | '/tickets'
    | '/time-off'
    | '/time-tracking'
    | '/training'
    | '/warranty-claims'
    | '/blog/$slug'
    | '/divisions/$slug'
    | '/help/$slug'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/meeting/$id'
    | '/portal/documents'
    | '/portal/invoices'
    | '/portal/jobs'
    | '/portal/messages'
    | '/divisions/'
    | '/portal/'
    | '/admin/company'
    | '/admin/departments'
    | '/clients/$id'
    | '/jobs/$id'
    | '/quotes/$id'
    | '/api/hq/assistant'
    | '/clients/'
    | '/jobs/'
    | '/quotes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/client-login'
    | '/contact'
    | '/faq'
    | '/help'
    | '/hq-login'
    | '/process'
    | '/projects'
    | '/services'
    | '/sitemap.xml'
    | '/accounting'
    | '/analytics'
    | '/applicants'
    | '/assistant'
    | '/calendar'
    | '/certifications'
    | '/change-orders'
    | '/channels'
    | '/company-tasks'
    | '/crews'
    | '/customer-timeline'
    | '/daily-logs'
    | '/dashboard'
    | '/deliveries'
    | '/dm'
    | '/drive'
    | '/employees'
    | '/eng-projects'
    | '/equipment'
    | '/expenses'
    | '/financial-reports'
    | '/hiring'
    | '/inspections'
    | '/inventory'
    | '/invoices'
    | '/job-costing'
    | '/kb'
    | '/leads'
    | '/live-chat'
    | '/mail'
    | '/meeting-notes'
    | '/meetings'
    | '/notifications'
    | '/onboarding'
    | '/org-chart'
    | '/permits'
    | '/phone'
    | '/pipeline'
    | '/plans'
    | '/profile'
    | '/proposals'
    | '/punch-list'
    | '/purchase-orders'
    | '/rd-ideas'
    | '/receiving'
    | '/resource-planning'
    | '/reviews'
    | '/rfis'
    | '/safety'
    | '/sales-analytics'
    | '/search'
    | '/settings'
    | '/subcontractors'
    | '/suppliers'
    | '/takeoffs'
    | '/tasks'
    | '/tickets'
    | '/time-off'
    | '/time-tracking'
    | '/training'
    | '/warranty-claims'
    | '/blog/$slug'
    | '/divisions/$slug'
    | '/help/$slug'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/meeting/$id'
    | '/portal/documents'
    | '/portal/invoices'
    | '/portal/jobs'
    | '/portal/messages'
    | '/divisions'
    | '/portal'
    | '/admin/company'
    | '/admin/departments'
    | '/clients/$id'
    | '/jobs/$id'
    | '/quotes/$id'
    | '/api/hq/assistant'
    | '/clients'
    | '/jobs'
    | '/quotes'
  id:
    | '__root__'
    | '/'
    | '/_hq'
    | '/about'
    | '/blog'
    | '/careers'
    | '/client-login'
    | '/contact'
    | '/faq'
    | '/help'
    | '/hq-login'
    | '/portal'
    | '/process'
    | '/projects'
    | '/services'
    | '/sitemap.xml'
    | '/_hq/accounting'
    | '/_hq/analytics'
    | '/_hq/applicants'
    | '/_hq/assistant'
    | '/_hq/calendar'
    | '/_hq/certifications'
    | '/_hq/change-orders'
    | '/_hq/channels'
    | '/_hq/clients'
    | '/_hq/company-tasks'
    | '/_hq/crews'
    | '/_hq/customer-timeline'
    | '/_hq/daily-logs'
    | '/_hq/dashboard'
    | '/_hq/deliveries'
    | '/_hq/dm'
    | '/_hq/drive'
    | '/_hq/employees'
    | '/_hq/eng-projects'
    | '/_hq/equipment'
    | '/_hq/expenses'
    | '/_hq/financial-reports'
    | '/_hq/help'
    | '/_hq/hiring'
    | '/_hq/inspections'
    | '/_hq/inventory'
    | '/_hq/invoices'
    | '/_hq/job-costing'
    | '/_hq/jobs'
    | '/_hq/kb'
    | '/_hq/leads'
    | '/_hq/live-chat'
    | '/_hq/mail'
    | '/_hq/meeting-notes'
    | '/_hq/meetings'
    | '/_hq/notifications'
    | '/_hq/onboarding'
    | '/_hq/org-chart'
    | '/_hq/permits'
    | '/_hq/phone'
    | '/_hq/pipeline'
    | '/_hq/plans'
    | '/_hq/profile'
    | '/_hq/proposals'
    | '/_hq/punch-list'
    | '/_hq/purchase-orders'
    | '/_hq/quotes'
    | '/_hq/rd-ideas'
    | '/_hq/receiving'
    | '/_hq/resource-planning'
    | '/_hq/reviews'
    | '/_hq/rfis'
    | '/_hq/safety'
    | '/_hq/sales-analytics'
    | '/_hq/search'
    | '/_hq/settings'
    | '/_hq/subcontractors'
    | '/_hq/suppliers'
    | '/_hq/takeoffs'
    | '/_hq/tasks'
    | '/_hq/tickets'
    | '/_hq/time-off'
    | '/_hq/time-tracking'
    | '/_hq/training'
    | '/_hq/warranty-claims'
    | '/blog/$slug'
    | '/divisions/$slug'
    | '/help/$slug'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/meeting/$id'
    | '/portal/documents'
    | '/portal/invoices'
    | '/portal/jobs'
    | '/portal/messages'
    | '/divisions/'
    | '/portal/'
    | '/_hq/admin/company'
    | '/_hq/admin/departments'
    | '/_hq/clients/$id'
    | '/_hq/jobs/$id'
    | '/_hq/quotes/$id'
    | '/api/hq/assistant'
    | '/_hq/clients/'
    | '/_hq/jobs/'
    | '/_hq/quotes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HqRoute: typeof HqRouteWithChildren
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  CareersRoute: typeof CareersRoute
  ClientLoginRoute: typeof ClientLoginRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HelpRoute: typeof HelpRouteWithChildren
  HqLoginRoute: typeof HqLoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  ProcessRoute: typeof ProcessRoute
  ProjectsRoute: typeof ProjectsRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DivisionsSlugRoute: typeof DivisionsSlugRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  MeetingIdRoute: typeof MeetingIdRoute
  DivisionsIndexRoute: typeof DivisionsIndexRoute
  ApiHqAssistantRoute: typeof ApiHqAssistantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq-login': {
      id: '/hq-login'
      path: '/hq-login'
      fullPath: '/hq-login'
      preLoaderRoute: typeof HqLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-login': {
      id: '/client-login'
      path: '/client-login'
      fullPath: '/client-login'
      preLoaderRoute: typeof ClientLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_hq': {
      id: '/_hq'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/divisions/': {
      id: '/divisions/'
      path: '/divisions'
      fullPath: '/divisions/'
      preLoaderRoute: typeof DivisionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/messages': {
      id: '/portal/messages'
      path: '/messages'
      fullPath: '/portal/messages'
      preLoaderRoute: typeof PortalMessagesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/jobs': {
      id: '/portal/jobs'
      path: '/jobs'
      fullPath: '/portal/jobs'
      preLoaderRoute: typeof PortalJobsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/invoices': {
      id: '/portal/invoices'
      path: '/invoices'
      fullPath: '/portal/invoices'
      preLoaderRoute: typeof PortalInvoicesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/documents': {
      id: '/portal/documents'
      path: '/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof PortalDocumentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/meeting/$id': {
      id: '/meeting/$id'
      path: '/meeting/$id'
      fullPath: '/meeting/$id'
      preLoaderRoute: typeof MeetingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/$slug': {
      id: '/help/$slug'
      path: '/$slug'
      fullPath: '/help/$slug'
      preLoaderRoute: typeof HelpSlugRouteImport
      parentRoute: typeof HelpRoute
    }
    '/divisions/$slug': {
      id: '/divisions/$slug'
      path: '/divisions/$slug'
      fullPath: '/divisions/$slug'
      preLoaderRoute: typeof DivisionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_hq/warranty-claims': {
      id: '/_hq/warranty-claims'
      path: '/warranty-claims'
      fullPath: '/warranty-claims'
      preLoaderRoute: typeof HqWarrantyClaimsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/training': {
      id: '/_hq/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof HqTrainingRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/time-tracking': {
      id: '/_hq/time-tracking'
      path: '/time-tracking'
      fullPath: '/time-tracking'
      preLoaderRoute: typeof HqTimeTrackingRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/time-off': {
      id: '/_hq/time-off'
      path: '/time-off'
      fullPath: '/time-off'
      preLoaderRoute: typeof HqTimeOffRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/tickets': {
      id: '/_hq/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof HqTicketsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/tasks': {
      id: '/_hq/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof HqTasksRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/takeoffs': {
      id: '/_hq/takeoffs'
      path: '/takeoffs'
      fullPath: '/takeoffs'
      preLoaderRoute: typeof HqTakeoffsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/suppliers': {
      id: '/_hq/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof HqSuppliersRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/subcontractors': {
      id: '/_hq/subcontractors'
      path: '/subcontractors'
      fullPath: '/subcontractors'
      preLoaderRoute: typeof HqSubcontractorsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/settings': {
      id: '/_hq/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof HqSettingsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/search': {
      id: '/_hq/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof HqSearchRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/sales-analytics': {
      id: '/_hq/sales-analytics'
      path: '/sales-analytics'
      fullPath: '/sales-analytics'
      preLoaderRoute: typeof HqSalesAnalyticsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/safety': {
      id: '/_hq/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof HqSafetyRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/rfis': {
      id: '/_hq/rfis'
      path: '/rfis'
      fullPath: '/rfis'
      preLoaderRoute: typeof HqRfisRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/reviews': {
      id: '/_hq/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof HqReviewsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/resource-planning': {
      id: '/_hq/resource-planning'
      path: '/resource-planning'
      fullPath: '/resource-planning'
      preLoaderRoute: typeof HqResourcePlanningRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/receiving': {
      id: '/_hq/receiving'
      path: '/receiving'
      fullPath: '/receiving'
      preLoaderRoute: typeof HqReceivingRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/rd-ideas': {
      id: '/_hq/rd-ideas'
      path: '/rd-ideas'
      fullPath: '/rd-ideas'
      preLoaderRoute: typeof HqRdIdeasRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/quotes': {
      id: '/_hq/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof HqQuotesRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/purchase-orders': {
      id: '/_hq/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof HqPurchaseOrdersRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/punch-list': {
      id: '/_hq/punch-list'
      path: '/punch-list'
      fullPath: '/punch-list'
      preLoaderRoute: typeof HqPunchListRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/proposals': {
      id: '/_hq/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof HqProposalsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/profile': {
      id: '/_hq/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof HqProfileRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/plans': {
      id: '/_hq/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof HqPlansRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/pipeline': {
      id: '/_hq/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof HqPipelineRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/phone': {
      id: '/_hq/phone'
      path: '/phone'
      fullPath: '/phone'
      preLoaderRoute: typeof HqPhoneRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/permits': {
      id: '/_hq/permits'
      path: '/permits'
      fullPath: '/permits'
      preLoaderRoute: typeof HqPermitsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/org-chart': {
      id: '/_hq/org-chart'
      path: '/org-chart'
      fullPath: '/org-chart'
      preLoaderRoute: typeof HqOrgChartRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/onboarding': {
      id: '/_hq/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof HqOnboardingRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/notifications': {
      id: '/_hq/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof HqNotificationsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/meetings': {
      id: '/_hq/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof HqMeetingsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/meeting-notes': {
      id: '/_hq/meeting-notes'
      path: '/meeting-notes'
      fullPath: '/meeting-notes'
      preLoaderRoute: typeof HqMeetingNotesRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/mail': {
      id: '/_hq/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof HqMailRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/live-chat': {
      id: '/_hq/live-chat'
      path: '/live-chat'
      fullPath: '/live-chat'
      preLoaderRoute: typeof HqLiveChatRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/leads': {
      id: '/_hq/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof HqLeadsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/kb': {
      id: '/_hq/kb'
      path: '/kb'
      fullPath: '/kb'
      preLoaderRoute: typeof HqKbRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/jobs': {
      id: '/_hq/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof HqJobsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/job-costing': {
      id: '/_hq/job-costing'
      path: '/job-costing'
      fullPath: '/job-costing'
      preLoaderRoute: typeof HqJobCostingRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/invoices': {
      id: '/_hq/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof HqInvoicesRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/inventory': {
      id: '/_hq/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof HqInventoryRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/inspections': {
      id: '/_hq/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof HqInspectionsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/hiring': {
      id: '/_hq/hiring'
      path: '/hiring'
      fullPath: '/hiring'
      preLoaderRoute: typeof HqHiringRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/help': {
      id: '/_hq/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HqHelpRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/financial-reports': {
      id: '/_hq/financial-reports'
      path: '/financial-reports'
      fullPath: '/financial-reports'
      preLoaderRoute: typeof HqFinancialReportsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/expenses': {
      id: '/_hq/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof HqExpensesRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/equipment': {
      id: '/_hq/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof HqEquipmentRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/eng-projects': {
      id: '/_hq/eng-projects'
      path: '/eng-projects'
      fullPath: '/eng-projects'
      preLoaderRoute: typeof HqEngProjectsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/employees': {
      id: '/_hq/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof HqEmployeesRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/drive': {
      id: '/_hq/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof HqDriveRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/dm': {
      id: '/_hq/dm'
      path: '/dm'
      fullPath: '/dm'
      preLoaderRoute: typeof HqDmRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/deliveries': {
      id: '/_hq/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof HqDeliveriesRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/dashboard': {
      id: '/_hq/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof HqDashboardRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/daily-logs': {
      id: '/_hq/daily-logs'
      path: '/daily-logs'
      fullPath: '/daily-logs'
      preLoaderRoute: typeof HqDailyLogsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/customer-timeline': {
      id: '/_hq/customer-timeline'
      path: '/customer-timeline'
      fullPath: '/customer-timeline'
      preLoaderRoute: typeof HqCustomerTimelineRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/crews': {
      id: '/_hq/crews'
      path: '/crews'
      fullPath: '/crews'
      preLoaderRoute: typeof HqCrewsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/company-tasks': {
      id: '/_hq/company-tasks'
      path: '/company-tasks'
      fullPath: '/company-tasks'
      preLoaderRoute: typeof HqCompanyTasksRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/clients': {
      id: '/_hq/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof HqClientsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/channels': {
      id: '/_hq/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof HqChannelsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/change-orders': {
      id: '/_hq/change-orders'
      path: '/change-orders'
      fullPath: '/change-orders'
      preLoaderRoute: typeof HqChangeOrdersRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/certifications': {
      id: '/_hq/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof HqCertificationsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/calendar': {
      id: '/_hq/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof HqCalendarRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/assistant': {
      id: '/_hq/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof HqAssistantRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/applicants': {
      id: '/_hq/applicants'
      path: '/applicants'
      fullPath: '/applicants'
      preLoaderRoute: typeof HqApplicantsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/analytics': {
      id: '/_hq/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof HqAnalyticsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/accounting': {
      id: '/_hq/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof HqAccountingRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/quotes/': {
      id: '/_hq/quotes/'
      path: '/'
      fullPath: '/quotes/'
      preLoaderRoute: typeof HqQuotesIndexRouteImport
      parentRoute: typeof HqQuotesRoute
    }
    '/_hq/jobs/': {
      id: '/_hq/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof HqJobsIndexRouteImport
      parentRoute: typeof HqJobsRoute
    }
    '/_hq/clients/': {
      id: '/_hq/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof HqClientsIndexRouteImport
      parentRoute: typeof HqClientsRoute
    }
    '/api/hq/assistant': {
      id: '/api/hq/assistant'
      path: '/api/hq/assistant'
      fullPath: '/api/hq/assistant'
      preLoaderRoute: typeof ApiHqAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_hq/quotes/$id': {
      id: '/_hq/quotes/$id'
      path: '/$id'
      fullPath: '/quotes/$id'
      preLoaderRoute: typeof HqQuotesIdRouteImport
      parentRoute: typeof HqQuotesRoute
    }
    '/_hq/jobs/$id': {
      id: '/_hq/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof HqJobsIdRouteImport
      parentRoute: typeof HqJobsRoute
    }
    '/_hq/clients/$id': {
      id: '/_hq/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof HqClientsIdRouteImport
      parentRoute: typeof HqClientsRoute
    }
    '/_hq/admin/departments': {
      id: '/_hq/admin/departments'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof HqAdminDepartmentsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/admin/company': {
      id: '/_hq/admin/company'
      path: '/admin/company'
      fullPath: '/admin/company'
      preLoaderRoute: typeof HqAdminCompanyRouteImport
      parentRoute: typeof HqRoute
    }
  }
}

interface HqClientsRouteChildren {
  HqClientsIdRoute: typeof HqClientsIdRoute
  HqClientsIndexRoute: typeof HqClientsIndexRoute
}

const HqClientsRouteChildren: HqClientsRouteChildren = {
  HqClientsIdRoute: HqClientsIdRoute,
  HqClientsIndexRoute: HqClientsIndexRoute,
}

const HqClientsRouteWithChildren = HqClientsRoute._addFileChildren(
  HqClientsRouteChildren,
)

interface HqJobsRouteChildren {
  HqJobsIdRoute: typeof HqJobsIdRoute
  HqJobsIndexRoute: typeof HqJobsIndexRoute
}

const HqJobsRouteChildren: HqJobsRouteChildren = {
  HqJobsIdRoute: HqJobsIdRoute,
  HqJobsIndexRoute: HqJobsIndexRoute,
}

const HqJobsRouteWithChildren =
  HqJobsRoute._addFileChildren(HqJobsRouteChildren)

interface HqQuotesRouteChildren {
  HqQuotesIdRoute: typeof HqQuotesIdRoute
  HqQuotesIndexRoute: typeof HqQuotesIndexRoute
}

const HqQuotesRouteChildren: HqQuotesRouteChildren = {
  HqQuotesIdRoute: HqQuotesIdRoute,
  HqQuotesIndexRoute: HqQuotesIndexRoute,
}

const HqQuotesRouteWithChildren = HqQuotesRoute._addFileChildren(
  HqQuotesRouteChildren,
)

interface HqRouteChildren {
  HqAccountingRoute: typeof HqAccountingRoute
  HqAnalyticsRoute: typeof HqAnalyticsRoute
  HqApplicantsRoute: typeof HqApplicantsRoute
  HqAssistantRoute: typeof HqAssistantRoute
  HqCalendarRoute: typeof HqCalendarRoute
  HqCertificationsRoute: typeof HqCertificationsRoute
  HqChangeOrdersRoute: typeof HqChangeOrdersRoute
  HqChannelsRoute: typeof HqChannelsRoute
  HqClientsRoute: typeof HqClientsRouteWithChildren
  HqCompanyTasksRoute: typeof HqCompanyTasksRoute
  HqCrewsRoute: typeof HqCrewsRoute
  HqCustomerTimelineRoute: typeof HqCustomerTimelineRoute
  HqDailyLogsRoute: typeof HqDailyLogsRoute
  HqDashboardRoute: typeof HqDashboardRoute
  HqDeliveriesRoute: typeof HqDeliveriesRoute
  HqDmRoute: typeof HqDmRoute
  HqDriveRoute: typeof HqDriveRoute
  HqEmployeesRoute: typeof HqEmployeesRoute
  HqEngProjectsRoute: typeof HqEngProjectsRoute
  HqEquipmentRoute: typeof HqEquipmentRoute
  HqExpensesRoute: typeof HqExpensesRoute
  HqFinancialReportsRoute: typeof HqFinancialReportsRoute
  HqHelpRoute: typeof HqHelpRoute
  HqHiringRoute: typeof HqHiringRoute
  HqInspectionsRoute: typeof HqInspectionsRoute
  HqInventoryRoute: typeof HqInventoryRoute
  HqInvoicesRoute: typeof HqInvoicesRoute
  HqJobCostingRoute: typeof HqJobCostingRoute
  HqJobsRoute: typeof HqJobsRouteWithChildren
  HqKbRoute: typeof HqKbRoute
  HqLeadsRoute: typeof HqLeadsRoute
  HqLiveChatRoute: typeof HqLiveChatRoute
  HqMailRoute: typeof HqMailRoute
  HqMeetingNotesRoute: typeof HqMeetingNotesRoute
  HqMeetingsRoute: typeof HqMeetingsRoute
  HqNotificationsRoute: typeof HqNotificationsRoute
  HqOnboardingRoute: typeof HqOnboardingRoute
  HqOrgChartRoute: typeof HqOrgChartRoute
  HqPermitsRoute: typeof HqPermitsRoute
  HqPhoneRoute: typeof HqPhoneRoute
  HqPipelineRoute: typeof HqPipelineRoute
  HqPlansRoute: typeof HqPlansRoute
  HqProfileRoute: typeof HqProfileRoute
  HqProposalsRoute: typeof HqProposalsRoute
  HqPunchListRoute: typeof HqPunchListRoute
  HqPurchaseOrdersRoute: typeof HqPurchaseOrdersRoute
  HqQuotesRoute: typeof HqQuotesRouteWithChildren
  HqRdIdeasRoute: typeof HqRdIdeasRoute
  HqReceivingRoute: typeof HqReceivingRoute
  HqResourcePlanningRoute: typeof HqResourcePlanningRoute
  HqReviewsRoute: typeof HqReviewsRoute
  HqRfisRoute: typeof HqRfisRoute
  HqSafetyRoute: typeof HqSafetyRoute
  HqSalesAnalyticsRoute: typeof HqSalesAnalyticsRoute
  HqSearchRoute: typeof HqSearchRoute
  HqSettingsRoute: typeof HqSettingsRoute
  HqSubcontractorsRoute: typeof HqSubcontractorsRoute
  HqSuppliersRoute: typeof HqSuppliersRoute
  HqTakeoffsRoute: typeof HqTakeoffsRoute
  HqTasksRoute: typeof HqTasksRoute
  HqTicketsRoute: typeof HqTicketsRoute
  HqTimeOffRoute: typeof HqTimeOffRoute
  HqTimeTrackingRoute: typeof HqTimeTrackingRoute
  HqTrainingRoute: typeof HqTrainingRoute
  HqWarrantyClaimsRoute: typeof HqWarrantyClaimsRoute
  HqAdminCompanyRoute: typeof HqAdminCompanyRoute
  HqAdminDepartmentsRoute: typeof HqAdminDepartmentsRoute
}

const HqRouteChildren: HqRouteChildren = {
  HqAccountingRoute: HqAccountingRoute,
  HqAnalyticsRoute: HqAnalyticsRoute,
  HqApplicantsRoute: HqApplicantsRoute,
  HqAssistantRoute: HqAssistantRoute,
  HqCalendarRoute: HqCalendarRoute,
  HqCertificationsRoute: HqCertificationsRoute,
  HqChangeOrdersRoute: HqChangeOrdersRoute,
  HqChannelsRoute: HqChannelsRoute,
  HqClientsRoute: HqClientsRouteWithChildren,
  HqCompanyTasksRoute: HqCompanyTasksRoute,
  HqCrewsRoute: HqCrewsRoute,
  HqCustomerTimelineRoute: HqCustomerTimelineRoute,
  HqDailyLogsRoute: HqDailyLogsRoute,
  HqDashboardRoute: HqDashboardRoute,
  HqDeliveriesRoute: HqDeliveriesRoute,
  HqDmRoute: HqDmRoute,
  HqDriveRoute: HqDriveRoute,
  HqEmployeesRoute: HqEmployeesRoute,
  HqEngProjectsRoute: HqEngProjectsRoute,
  HqEquipmentRoute: HqEquipmentRoute,
  HqExpensesRoute: HqExpensesRoute,
  HqFinancialReportsRoute: HqFinancialReportsRoute,
  HqHelpRoute: HqHelpRoute,
  HqHiringRoute: HqHiringRoute,
  HqInspectionsRoute: HqInspectionsRoute,
  HqInventoryRoute: HqInventoryRoute,
  HqInvoicesRoute: HqInvoicesRoute,
  HqJobCostingRoute: HqJobCostingRoute,
  HqJobsRoute: HqJobsRouteWithChildren,
  HqKbRoute: HqKbRoute,
  HqLeadsRoute: HqLeadsRoute,
  HqLiveChatRoute: HqLiveChatRoute,
  HqMailRoute: HqMailRoute,
  HqMeetingNotesRoute: HqMeetingNotesRoute,
  HqMeetingsRoute: HqMeetingsRoute,
  HqNotificationsRoute: HqNotificationsRoute,
  HqOnboardingRoute: HqOnboardingRoute,
  HqOrgChartRoute: HqOrgChartRoute,
  HqPermitsRoute: HqPermitsRoute,
  HqPhoneRoute: HqPhoneRoute,
  HqPipelineRoute: HqPipelineRoute,
  HqPlansRoute: HqPlansRoute,
  HqProfileRoute: HqProfileRoute,
  HqProposalsRoute: HqProposalsRoute,
  HqPunchListRoute: HqPunchListRoute,
  HqPurchaseOrdersRoute: HqPurchaseOrdersRoute,
  HqQuotesRoute: HqQuotesRouteWithChildren,
  HqRdIdeasRoute: HqRdIdeasRoute,
  HqReceivingRoute: HqReceivingRoute,
  HqResourcePlanningRoute: HqResourcePlanningRoute,
  HqReviewsRoute: HqReviewsRoute,
  HqRfisRoute: HqRfisRoute,
  HqSafetyRoute: HqSafetyRoute,
  HqSalesAnalyticsRoute: HqSalesAnalyticsRoute,
  HqSearchRoute: HqSearchRoute,
  HqSettingsRoute: HqSettingsRoute,
  HqSubcontractorsRoute: HqSubcontractorsRoute,
  HqSuppliersRoute: HqSuppliersRoute,
  HqTakeoffsRoute: HqTakeoffsRoute,
  HqTasksRoute: HqTasksRoute,
  HqTicketsRoute: HqTicketsRoute,
  HqTimeOffRoute: HqTimeOffRoute,
  HqTimeTrackingRoute: HqTimeTrackingRoute,
  HqTrainingRoute: HqTrainingRoute,
  HqWarrantyClaimsRoute: HqWarrantyClaimsRoute,
  HqAdminCompanyRoute: HqAdminCompanyRoute,
  HqAdminDepartmentsRoute: HqAdminDepartmentsRoute,
}

const HqRouteWithChildren = HqRoute._addFileChildren(HqRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface HelpRouteChildren {
  HelpSlugRoute: typeof HelpSlugRoute
}

const HelpRouteChildren: HelpRouteChildren = {
  HelpSlugRoute: HelpSlugRoute,
}

const HelpRouteWithChildren = HelpRoute._addFileChildren(HelpRouteChildren)

interface PortalRouteChildren {
  PortalDocumentsRoute: typeof PortalDocumentsRoute
  PortalInvoicesRoute: typeof PortalInvoicesRoute
  PortalJobsRoute: typeof PortalJobsRoute
  PortalMessagesRoute: typeof PortalMessagesRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalDocumentsRoute: PortalDocumentsRoute,
  PortalInvoicesRoute: PortalInvoicesRoute,
  PortalJobsRoute: PortalJobsRoute,
  PortalMessagesRoute: PortalMessagesRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HqRoute: HqRouteWithChildren,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  CareersRoute: CareersRoute,
  ClientLoginRoute: ClientLoginRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HelpRoute: HelpRouteWithChildren,
  HqLoginRoute: HqLoginRoute,
  PortalRoute: PortalRouteWithChildren,
  ProcessRoute: ProcessRoute,
  ProjectsRoute: ProjectsRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DivisionsSlugRoute: DivisionsSlugRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  MeetingIdRoute: MeetingIdRoute,
  DivisionsIndexRoute: DivisionsIndexRoute,
  ApiHqAssistantRoute: ApiHqAssistantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
